sudo: false

language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

os:
- osx
- linux
- windows

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run ci-lint; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run test; else npm run ci-test; fi
  - npm run check

after_success:
  - bash <(curl -s https://codecov.io/bash) -c -Z -f coverage/lcov.info
